auth_app/urls.py
from django.urls import path
from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('register', views.registration, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('success', views.login_success, name="login_success"),
    path('register-success', views.register_success, name="registration_success")
]

auth_project/urls.py
from django.contrib import admin
from django.urls import path, include

from auth_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('auth_app/', include('auth_app.urls'))
]

auth_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileModel(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileModel


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileModel
        fields = ('profile_pic', 'portfolio_link')


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "password")

auth_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from auth_app.forms import UserLoginForm, UserForm, UserProfileForm

# Create your views here.


def index(request):
    return render(request, 'auth_app/index.html')


def registration(request):
    user_form = UserForm()
    profile_form = UserProfileForm()

    is_registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            is_registered = True

        else:
            print(user_form.errors, profile_form.errors)

    return render(request, 'auth_app/registration.html', {'user_form': user_form, 'user_profile_form': profile_form, 'is_registered': is_registered})


def user_login(request):
    login_form = UserLoginForm()

    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        print("username", username, password)
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('success')
            else:
                return HttpResponse("Account not active")
        else:
            return HttpResponse("Invalid user")

    return render(request, 'auth_app/login.html', {'form': login_form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def login_success(request):
    return render(request, 'auth_app/success.html')


def register_success(request):
    return render(request, 'auth_app/registration_success.html')

templates/auth_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Authenticator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_app:register' %}">Register</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_app:logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_app:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <div>
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
</body>
</html>

templates/auth_app/index.html
<!DOCTYPE html>
{% extends 'auth_app/base.html' %}
    {% block body_block %}
            <h1>I am index</h1>
    {% endblock %}

templates/auth_app/login.html
<!DOCTYPE html>
{% extends 'auth_app/base.html' %}
    {% block body_block %}
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" title="Submit" />
        </form>
    {% endblock %}

templates/auth_app/registration.html
<!DOCTYPE html>
{% extends 'auth_app/base.html' %}
    {% block body_block %}
        <form enctype="multipart/form-data"  method="POST">
            {{user_form.as_p}}
            {{user_profile_form.as_p}}
            {% csrf_token %}
            <input type="submit" title="Submit" />
        </form>
    {% endblock %}
    <!-- action="{% url 'auth_app:registration_success' %}" -->

templates/auth_app/registration_success.html
<!DOCTYPE html>
{% extends 'auth_app/base.html' %}
    {% block body_block %}
        <h1>Successfully Registered</h1>
    {% endblock %}

templates/auth_app/success.html
<!DOCTYPE html>
{% extends 'auth_app/base.html' %}
    {% block body_block %}
        <h1>Successfully logged in</h1>
    {% endblock %}